### ISSUE TITLE
Предлагается добавить haskell-чятик в gitter

### ISSUE THREAD

**Issue by afiskon** [mr-mig/ru-it-chats#20]
https://gitter.im/denisshevchenko/haskell

Овер 100 человек онлайн

**Comment by mr-mig** [comment]
Предлагаешь его под зонтик dev-ua добавить?

**Comment by mr-mig** [comment]
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/dev-ua/haskell)
