### ISSUE TITLE
Haxe/Flash

### ISSUE THREAD

**Issue by andrew-git** [mr-mig/ru-it-chats#37]
Спасибо за подборку!

Haxe чат также есть в Slack https://haxe.slack.com/, получить инвайт можно здесь http://haxe.ru/haxe_chat
Flash skype-чат skype:?chat&blob=KW56YnFUC8Mx-Y5WEialjGB7-pLRz3TpT7KUk3KFMJ4bdiTc4NqAM38xjlxB5tiYqg15VtBYoMI

**Comment by mr-mig** [comment]
Merged :+1:

**Comment by andrew-git** [comment]
Thanks!
