### ISSUE TITLE
Не отображается teaser.jpg

### ISSUE THREAD

**Issue by dbellkoff** [mr-mig/ru-it-chats#59]
Не отображается teaser.jpg на firefox, но показывается на chrome
![2015-12-29 16 05 16](https://cloud.githubusercontent.com/assets/10268787/12033546/006ef8b2-ae46-11e5-92ff-389cf0b4bca1.png)

**Comment by mr-mig** [comment]
Какой фаерфокс такое делает? У меня всё на месте, больше жалоб тоже не было.

**Comment by dbellkoff** [comment]
Разобрался, **Adblock Pluse**  блокирует тизер
