### ISSUE TITLE
Почему README на английском?

### ISSUE THREAD

**Issue by mkpankov** [mr-mig/ru-it-chats#68]
Поскольку это список русскоязычных чатов, я думаю, логично, если бы и описание было на русском.

**Comment by iGusev** [comment]
Это список рускоязычных IT-чатов)

**Comment by mr-mig** [comment]
Так сложилось исторически. Я в рабочих инструментах думаю на английском. 
У вас есть возможность это исправить ;)

**Comment by mkpankov** [comment]
Хорошо, сделаю PR
