### ISSUE TITLE
#javascript — 404

### ISSUE THREAD

**Issue by Ohar** [mr-mig/ru-it-chats#71]
javascript, nodejs, angularjs, ... 	IRC: learn.javascript.ru/chat

**Comment by mr-mig** [comment]
PR please

**Comment by mr-mig** [comment]
Может @iliakan нам свет прольёт?

**Comment by iliakan** [comment]
Oh, это старая ссылка, новая: https://slack.javascript.ru

**Comment by mr-mig** [comment]
Спасибо за апдейт. Фиксед.
