### ISSUE TITLE
Чаты QA

### ISSUE THREAD

**Issue by naffix** [mr-mig/ru-it-chats#78]
Пожалуйста добавь  из списка на странице http://www.qaclub.by/about/skype-chats-for-testers/

**Comment by mr-mig** [comment]
Годнота, сделаем!

**Comment by mr-mig** [comment]
Эти чаты живые? 
"QAC: General testing principles" и "QAC: Management in testing." показывают мне в районе 10 участников

**Comment by msalnikov** [comment]
Самый большой, живой интернациональный чат тестировщика в Slack. Для получения инвайта нужно указать e-mail здесь 
https://software-testers.herokuapp.com/

**Comment by naffix** [comment]
Неплохой чат - плюсую

Best regards,

Anton Tryfanau

Mob: +375298397310

Email: anton.tryfanau@gmail.com

Skype:  anton_tryfanau

2016-04-21 9:37 GMT+03:00 Maxim <notifications@github.com>:

**Comment by iGusev** [comment]
@msalnikov уже есть в списке этот чат

**Comment by mr-mig** [comment]
Все живые чаты добавлены
